### ISSUE TITLE
[Bug] bin/console d:conf flagception failed with error "The extension with alias "flagception" does not have its getConfiguration() method setup"

### ISSUE THREAD

**Issue by hanovruslan** [playox/flagception-bundle#22]
`bin/console d:conf flagception` (or ` ... FlagceptionBundle`)

failed with error 

> The extension with alias "flagception" does not have its getConfiguration() method setup 

symfony 6.3.8

**Comment by teiling88** [comment]
Can you provide some additional information how to fix that please?
thanks

**Comment by hanovruslan** [comment]
Hi!

I'm sorry what kind of additional information can i provide?
But anyway ....
These are some of key deps of my project

- symfony/* - 6.3.*
- flagception/flagception - 1.9.1
- flagception/flagception-bundle - 4.4.1 

my flagception config

```yml
flagception:
    features:
        demo_123:
            default: true
        demo_456:
            default: true
        feature_5:
            default: false
        feature_6:
            default: true
    activators:
        environment:
            enable: false
```

how to see error - try to run command

```bash
bin/console d:conf FlagceptionBundle
```
or
```bash
bin/console d:conf flagception
```

Error message
```
The extension with alias "flagception" does not have its getConfiguration() method setup.
```

for now i've override some of this bundle methods in order to temp fix this error

```
use Flagception\Bundle\FlagceptionBundle\DependencyInjection\FlagceptionExtension as BaseFlagceptionExtension;

class FlagceptionExtension extends BaseFlagceptionExtension
{
    public function load(array $configs, ContainerBuilder $container): void
    {
        $loader = new Loader\YamlFileLoader($container, new FileLocator(__DIR__.'/../../../../resources/config/services/packages')); // relative path to my flagception.yml 
        $loader->load('flagception.yaml');
        parent::load($configs, $container);
    }

    public function getConfiguration(array $config, ContainerBuilder $container): Configuration
    {
        return new Configuration($this->getConfigurators($container));
    }

    private function getConfigurators(ContainerBuilder $container): array
    {
        $configurators = [];

        $services = $container->findTaggedServiceIds('flagception.configurator');
        foreach (array_keys($services) as $id) {
            $configurator = $container->get($id);
            $configurators[str_replace('-', '_', (string) $configurator->getKey())] = $configurator;
        }

        return $configurators;
    }
}
```
